controllers:
    resource: ../src/Controller/
    type: annotation


admin_login:
    path: /admin/login
    controller: App\Controller\AdminController::login

home:
    path: /
    controller: App\Controller\HomeController::index

formation:
    path: /formation
    controller: App\Controller\FormationController::index

projet:
    path: /projet
    controller: App\Controller\ProjetController::index


