# services.yaml

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    # Placez vos paramètres ici, s'ils ne doivent pas changer selon l'environnement de déploiement.

services:
    # Configuration par défaut pour les services dans ce fichier
    _defaults:
        autowire: true      # Injection automatique des dépendances dans vos services.
        autoconfigure: true # Enregistrement automatique de vos services en tant que commandes, abonnés d'événements, etc.
        bind:
            $projectDir: '%kernel.project_dir%'

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Controller\BackOffice\Experience\:
        resource: '../src/Controller/BackOffice/Experience/*'

    App\Controller\FrontOffice\:
        resource: '../src/Controller/FrontOffice'
        tags: ['controller.service_arguments']

    App\Form\:
        resource: '../src/Form'
        tags: ['form.type']

imports:
    - { resource: custom_parameters.yaml }  # Importez d'autres fichiers de configuration si nécessaire.
